[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
solc = "0.8.19"
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
via_ir = true

[profile.lite]
optimizer = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config